Islandora-CLAW/CLAW

install/drupal.sh

Include XML_field module

---

install/drupal.sh

Don't re-add drupal to document root on a re-provisioning

---

docs/contributing/templates/closeCommitterVote.txt
docs/contributing/templates/committerAnnounce.txt
docs/contributing/templates/committerInvite.txt
docs/contributing/templates/committerInviteCLA.txt
docs/contributing/templates/committerVote.txt

I'll do a follow-up pull request to take care of updating committers.md.

Add committers templates.

---

docs/contributing/committers.md

Add @acoburn and @diegopino as committers.

---

camel/commands/bin/islandora.php
camel/component/pom.xml
camel/karaf/pom.xml
camel/pom.xml
camel/services/basic-image-service/pom.xml
camel/services/collection-service/pom.xml
camel/services/pom.xml
camel/sync/pom.xml
docs/technical-documentation/commands.md
docs/technical-documentation/islandora-component.md
install/configs/karaf/watch.script

Reverts Islandora-Labs/islandora#61

Revert "increment version to 0.0.1-SNAPSHOT"

---

install/README.md
install/Vagrantfile

Setup Vagrant providers for DigitalOcean and AWS. Address #52.

---

install/scripts/drupal.sh

We're indexing in Solr again.
Test 'COLLECTION' collection object:
```
{
"response":{"numFound":1,"start":0,"docs":[
{
"id":"5q66br/node/1",
"site":"http://localhost:8000/",
"hash":"5q66br",
"entity_id":1,
"entity_type":"node",
"bundle":"islandora_collection",
"bundle_name":"Collection",
"ss_language":"und",
"path":"node/1",
"url":"http://localhost:8000/node/1",
"label":"COLLECTION",
"spell":["COLLECTION",
" http://localhost:8080/fcrepo/rest/dd/e7/e1/f8/dde7e1f8-b96a-4de4-8a1b-c1dc3af96ecd http://localhost:8080/fcrepo/rest/ Coverage Creator "],
"content":" http://localhost:8080/fcrepo/rest/dd/e7/e1/f8/dde7e1f8-b96a-4de4-8a1b-c1dc3af96ecd http://localhost:8080/fcrepo/rest/ Coverage Creator ",
"teaser":" http://localhost:8080/fcrepo/rest/dd/e7/e1/f8/dde7e1f8-b96a-4de4-8a1b-c1dc3af96ecd …
```

Correctly deploy Drupal Solr configuration. Address #79.

---

docs/user-documentation/2xfor1x.md
mkdocs.yml

Create user-documentation folder and 2xfor1x stub

---

contributing.md

See #98 
@Islandora-Labs/7-x-2-x-committers and @Islandora-Labs/7-x-2-x-sprinters, please let me know what you think.
cheers!

Add weekly Tech Calls to contributing. Address #98

---

install/README.md

Changed the documentation to reflect the repositories new location for Issue #112

Changed the documentation to reflect the repositories new location for Issue #112

---

docs/contributing/committers.md
docs/index.md
docs/user-documentation/2xfor1x.md
docs/user-documentation/adding-object-to-collection-in-islandora-7.x-2.x.md
docs/user-documentation/creating-collections-in-islandora-7.x-2.x.md
docs/user-documentation/editing-basic-image-form-in-islandora-7.x-2.x.md
docs/user-documentation/form-field-select-taxonomy-in-islandora-7.x-2.x.md
mkdocs.yml

See: #117 
How to test: http://islandora-claw.github.io/CLAW/technical-documentation/docs-build/

Address MkDocs warnings, and clean up formatting. Address #117

---

drupal/islandora_basic_image/islandora_basic_image.module

Have not tested this thoroughly, but will as soon as I get out of meetings...

first draft fix for #93

---

camel/pom.xml
camel/services/basic-image-service/pom.xml
camel/services/basic-image-service/src/main/resources/OSGI-INF/blueprint/blueprint.xml
camel/services/basic-image-service/src/main/resources/OSGI-INF/blueprint/get.xml
camel/services/basic-image-service/src/test/java/ca/islandora/services/basic/image/GetRoutesTest.java
camel/services/basic-image-service/src/test/java/ca/islandora/services/basic/image/RestEndpointTest.java
camel/services/basic-image-service/src/test/java/ca/islandora/services/basic/image/SparqlRouteTest.java
camel/services/basic-image-service/src/test/resources/sparql.xml
camel/sync/pom.xml

Mostly this just adds tests, but it changes one thing with the routes, moving away from jsonpath, opting instead for xpath. The reason is that the dependency chain for jsonpath seems to cause problems for the testing framework.

added basic tests to image service

---

drupal/islandora/include/admin.form.inc
drupal/islandora_basic_image/islandora_basic_image.module
drupal/islandora_collection/islandora_collection.module
install/scripts/drupal.sh

Replaced hardcoded url's with variable calls.

Cleaned up pull

---

contributing.md

Update CONTRIBUTING.md since F4IG is deprecated.

---

install/README.md

Add shorthand command for `ssh -p 2222 vagrant@localhost`
`vagrant ssh`
#162 Documentation - SSH Shorthand

Update SSH access command

---

install/Vagrantfile
install/scripts/bootstrap.sh
install/scripts/drupal.sh
install/scripts/islandora-camel.sh
install/scripts/islandora-commands.sh
install/scripts/lamp-server.sh
install/scripts/solr.sh

first pass at addressing [#192](https://github.com/Islandora-CLAW/CLAW/issues/192) 
1. added -qq to apt-get commands
2. removed --verbose from cp and tar commands

Sprint 002

---

README.md
install/Vagrantfile

- updated README.md
- added ability to optionally use environment variables in install/Vagrantfile

make it easier to configure virtual box on the fly

---

README.md
install/README.md

Fix README edits from #198; Address #202

---

services/CollectionService/src/Controller/CollectionController.php
services/CollectionService/src/Provider/CollectionServiceProvider.php
services/CollectionService/templates/createIndirectContainerfromTS.json
services/CollectionService/templates/createOreProxy.json
services/ResourceService/src/Provider/ResourceServiceProvider.php
services/TransactionService/src/Provider/TransactionServiceProvider.php
services/src/index.php

Partially addresses #177 
I left the turtle templates there for now. In case they help anyone. We can leave them or remove them later.

Using JSON-LD internally

---

install/scripts/karaf.sh

Update karaf download links to use archive.apache.org; Address #218.

---

README.md

@DiegoPino can you merge this if you're cool with it before our presentation?

README updates/tweaks

---

install/README.md

Reverts Islandora-CLAW/CLAW#292 -- This should be in master, not 2.x

Revert "Update README.md"

---

install/scripts/fcrepo.sh

See: https://github.com/Islandora-CLAW/CLAW/issues/291

Address #291; Use fcrepo-webapp-plus instead of fcrepo-webapp.

---

docs/user-documentation/intro-to-claw.md

Updated Drupal section to make Drupal 8 primary, added info on RDF and LDP.
Linked Data section is 'manez explains concepts she barely grasps herself,' so please review throughly 😅 
If good, this should complete #261

Update intro-to-claw.md to complete #261

---

docs/user-documentation/intro-to-claw.md

Small update for clarity in the intro and a typo fix.

Update intro-to-claw.md - typo and intro update

---

README.md
docs/index.md

Addresses islandora-claw/claw#312

Update references to Danny's GitHub account

---

CONTRIBUTING.md

@dannylamb here is an easy one.

Update link to use case template.

---

README.md

If this language / placement works, great, otherwise feel free to close.

Add note for newbies on where to start; Address #319.

---

install/README.md

To complete Islandora-CLAW/CLAW#378

Update README.md - add vagrant version

---

install/scripts/drupal.sh

No more submodules in vagrant build! Address #424.

---

install/scripts/drupal.sh

Adding rules and typed_data to the install

---

.gitmodules

* Add submodules for:
* islandora_collection
* islandora_image
* Update the branches for existing submodules
Fixes Islandora-CLAW/CLAW#511

Add new submodules and update existing ones

---

README.md

@Islandora-CLAW/committers here is an easy one :smile:

Remove cruft, and update

---

.github/PULL_REQUEST_TEMPLATE.md

**GitHub Issue**: (link)
* https://github.com/Islandora-CLAW/CLAW/issues/541
* http://irclogs.islandora.ca/2017-03-01.html  
* Create a directory called: .github
* Create a file called: PULL_REQUEST_TEMPLATE.md
* In the template, paste in the contents of this comment https://github.com/Islandora-CLAW/CLAW/issues/541#issuecomment-283424037
A in-depth description of the changes made by this PR. Technical details and possible side effects.
* Provides a PR template in every CLAW repository you fork for ease of use.
* Read the template and verify that it is a good template. 
* Eeek, newbie pull request. 
Thanks @ruebot.

Amanda's Pull Request Template

---

docs/contributing/templates/closeCommitterVote.txt
docs/contributing/templates/committerAnnounce.txt
docs/contributing/templates/committerInvite.txt
docs/contributing/templates/committerInviteCLA.txt
docs/contributing/templates/committerVote.txt

Cleans up a couple typos, 7.x-2.x cruft, and whitespace.
Nothing
Make sure I don't introduce even more typos :-)
Easy one for @Islandora-CLAW/committers

doc cleanup

---

docs/contributing/committers.md

**GitHub Issue**:  None
Add @jonathangreen as a new CLAW committer!

Add @jonathangreen as a committer

---

.scripts/line_endings.sh
.scripts/php56.ini
.scripts/travis_setup_drupal.sh
.scripts/travis_setup_php.sh

https://github.com/Islandora-CLAW/CLAW/issues/585
Add the scripts to the central CLAW repository, then other pulls will use the scripts in other repos.
@dannylamb

Add travis scripts to CLAW repo

---

.scripts/travis_setup_drupal.sh

Fix issue with path I made in PR #586

Fix path in drupal setup script

---

.scripts/line_endings.sh

Part of:
https://github.com/Islandora-CLAW/CLAW/issues/585
Blocker for:
https://github.com/Islandora-CLAW/Crayfish/pull/19
https://github.com/Islandora-CLAW/Crayfish/pull/20
The old filter was too specific about what it was ignoring. In the case of nested repositories, it wouldn't properly filter. Should filter correctly now. 
@dannylamb

Update line endings script.

---

.gitmodules

Updates the commit hash for the claw_vagrant submodule to latest.
This is my first time working with submodules so you might wanna triple check that I did it the right way.
@dannylamb @ruebot

Updates claw_vagrant submodule to latest, and changes tabs to spaces in .gitmodules file

---

docs/user-documentation/CLAWfor1x.md
docs/user-documentation/intro-to-claw.md

**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/510
Minor updates to `/docs/user-documentation/` files
* Removes mention of PDX from stack description
* Updates Alpaca description to be more accurate
* Adds spaces between octothorps (#) and header text so GitHub displays it properly
* Slight wording changes for readability
Read it.
Any feedback on things to add would be helpful too, or at least reviewing what's already there for accuracy.

Minor updates in user-documentation

---

.gitmodules

Adds all current CLAW projects, and updates submodules. Getting ready for IslandoraCon, and planning out what a initial release would look like for the project.
A few submodules.
* Look at it, and make sure it makes sense?
@dannylamb

Add all project submodules in anticipation for IslandoraCon.

---

README.md
docs/chullo/README.md
docs/crayfish-commons/README.md
docs/crayfish/README.md
docs/jsonld/README.md
docs/syn/README.md
mkdocs.yml

* Pull in sub-modules to documentation
* Update mkdocs config
See above.
Verify symlinks work, and documentation builds.
I left drupal-project out of the documentation since it really isn't ours. Let me know if you want it in there.
@dannylamb

More update for the conference and upcoming initial release

---

README.md
docs/technical-documentation/versioning.md

Updates list of components in versioning policy, and fixes a relative link that breaks on the gh-pages version of the documentation.
Here is an easy one @Islandora-CLAW/committers

Update versioning policy to include current CLAW components.

---

docs/user-documentation/intro-to-ld-for-claw.md

**GitHub Issue**: None.
Fix the list formatting so it displays nice and pretty instead of in a big old blog.
@dannylamb

Fix formatting

---

.scripts/travis_setup_drupal.sh

Reverts Islandora-CLAW/CLAW#652 so we can test the other case for https://github.com/Islandora-CLAW/islandora/pull/64
Paging @ruebot

Revert "Fix TravisCI for https://github.com/Islandora-CLAW/CLAW/issues/643 re…"

---

.scripts/travis_setup_drupal.sh

**GitHub Issue**: #670
* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)
Follow up to these bad boys:
- #672 
- #673
Replaces `/var/www/html` with `/opt/drupal`
A in-depth description of the changes made by this PR. Technical details and possible side effects.
Merge and then restart Travis on islandora_collection

Issue 670 Part 2 - Electric Boogaloo

---

docs/islandora/rdf-mapping.md
mkdocs.yml

This PR adds a doc with notes to help update/create RDF mapping for drupal bundles.
* Review

Islandora documentation - RDF Mapping

---

.gitmodules

Removing claw-vagrant from docs and adding in claw-playbook.
Also updating the submodules.

Remove claw_vagrant and add claw-playbook

---

.scripts/php56.ini
.scripts/travis_setup_drupal.sh
.scripts/travis_setup_php.sh

**GitHub Issue**: https://github.com/Islandora-Devops/claw-playbook/pull/66 and https://github.com/Islandora-CLAW/CLAW/issues/841
Removes 5.6, unblocking https://github.com/Islandora-Devops/claw-playbook/pull/66 and https://github.com/Islandora-CLAW/CLAW/issues/841
No more PHP 5.6
We can fix https://github.com/Islandora-Devops/claw-playbook/pull/66 and https://github.com/Islandora-CLAW/CLAW/issues/841

Removing 5.6

---

docs/contributing/committers.md

Adds our latest Islandora CLAW Committer to the list 🎊 

Update Committers list to include rosiel

---

README.md

**GitHub Issue**: No issue. Just a comment from irc
* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)
Adds the 2019 meetings list to the readme. 
Hi @rangel35 !

Update README.md - add 2019 meetings link

---

.scripts/travis_setup_drupal.sh

**GitHub Issue**: Needed for https://github.com/Islandora-CLAW/islandora_demo/pull/16
Adds the composer optimization package, and also shoves everything into a single call to composer to eliminate an unnecessary control structure.
Merge it and Travis goes green when I reset the build for https://github.com/Islandora-CLAW/islandora_demo/pull/16

composer optimization for travis setup

---

docs/user-documentation/add-member-to-collection.md
docs/user-documentation/create-collection.md

Adds documentation about Creating a Collection and Adding a Member to a Collection.

added collection creation and create members docs

---

.scripts/travis_setup_drupal.sh

Gets Travis back on Drupal 8.6 so tests run again.
Merge this and restart all our failing builds.

Pinning travis to 8.6
