install/Vagrantfile, install/blazegraph.sh, install/fcrepo-camel-toolbox.sh, install/fuseki.sh
Adding in fcrepo-camel-toolbox for triplestore indexing
Adding BlazeGraph as a possible triplestore.
Allow environment variable TRIPLESTORE to choose the triplestore to install.
Assists in #30 
To use BlazeGraph run
```TRIPLESTORE=blazegraph vagrant up```
otherwise Fuseki is installed, but does not work yet.
=> Triplestore

camel/commands/bin/islandora.php, camel/component/pom.xml, camel/karaf/pom.xml, camel/pom.xml, camel/services/basic-image-service/pom.xml, camel/services/collection-service/pom.xml, camel/services/pom.xml, camel/sync/pom.xml, docs/technical-documentation/commands.md, docs/technical-documentation/islandora-component.md, install/configs/karaf/watch.script
A 0.0.0-SNAPSHOT version doesn't make any sense to me (we're not preparing for a 0.0.0 release).
This also removes a few superfluous version declarations from the pom files.
=> increment version to 0.0.1-SNAPSHOT

install/Vagrantfile
This resolves #76.
```
==> default: Forwarding ports...
default: 8080 => 8080 (adapter 1)
default: 8181 => 8181 (adapter 1)
default: 3306 => 3306 (adapter 1)
default: 5432 => 5432 (adapter 1)
default: 80 => 8000 (adapter 1)
default: 22 => 2222 (adapter 1)
```
=> Override port 80 mappings for additional providers. Address #76.

services/TransactionService/composer.json, services/TransactionService/config/settings.dev.yml, services/TransactionService/config/settings.yml, services/TransactionService/src/Controller/TransactionController.php, services/TransactionService/src/Provider/TransactionServiceProvider.php, services/TransactionService/src/index.php
This depends on https://github.com/Islandora-CLAW/chullo/pull/32 to correct the FedoraApi extendTransaction call.
=> Use ServiceProvider and ControllerProvider for the Transaction Service

services/CollectionService/composer.json, services/CollectionService/config/settings.dev.yml, services/CollectionService/config/settings.yml, services/CollectionService/src/index.php, services/CollectionService/templates/createIndirectContainerfromTS.sparql, services/CollectionService/templates/createIndirectContainerfromTS.ttl, services/CollectionService/templates/createPCDMCollectionfromTS.sparql, services/ResourceServiceProvider/composer.json, services/ResourceServiceProvider/config/settings.yml, services/ResourceServiceProvider/src/Provider/ResourceServiceProvider.php
Implements Collection Service with RDF aggregator.
Implements a pseudo monolithic PCDM Collection microservice implementation using ResourceServiceProvider
This services is built on one POST route, following the same logic as a ResourceService POST Route
Accepts and extra $uuid to be used as base resource for the PCDM collection 
Some updates to composer and ResourceServiceProvider (not breaking)
The collection Service accepts every RDF language/serialisation EasyRdf accepts via POST
Adds PCDM triples and UUID predicates (with an islandora experimental one) to given rdf body
If RDF body is empty it creates the resources too
Also: 
* Clean up of composer.json to use 0.0.2 chullo package
* Allows Resource Service Config yaml files to be overridden by implementing app
* Adds a common route …
=> Collection Service Implementation 

services/CollectionService/composer.lock, services/CollectionService/src/index.php
See Issue #149 
* Moved islandora resource service /members link header to rel="hub" (this is the indirect container) using iana.org definitions http://www.iana.org/assignments/link-relations/link-relations.xhtml
* Moved fedora REST's API location to rel="alternate", (this is the real path in Fedora4 world)
* Moved the base landora resource service url for the newly created PCDM collection object to header "Location" (this is the actual collection object)
and copied into body.
=> ISSUE-149: Changed final response in Collection Service

camel/sync/src/main/resources/OSGI-INF/blueprint/blueprint.xml, camel/sync/src/main/resources/OSGI-INF/blueprint/eventGateway.xml
This change alters the JSON requests for adding thumbnail's and medium size
images, such that the base64 encoding of the image file no longer includes CRLF
characters every 78 characters; which is the default behavoir for the camel
base64 marshal.
This didn't arise as an issue previously since the PHP 5.5 code recieving it
didn't validate the JSON and simply ignored the CRLF characters, for versions of
PHP >=5.6 JSON is now validated, so we must send valid JSON.
=> Fix invalid base64 in JSON requests

docs/contributing/contributing.md, docs/index.md, docs/technical-documentation/docs-build.md, mkdocs.yml
Address #174
Let me know if y'all want me to do a sprint-002 branch pull too.
Once this is merged, I'll push to ghpages.
=> Change Mkdocs theme, and update documentation; Address #174.

.gitattributes, README.md, install/README.md, install/Vagrantfile
Added .gitattribute to resolve line ending issues on Windows computers when attempting to Vagrant up. Resolves #188.
Note: requires a Windows test before merge.
=> Change line ending behavior, per #188

docs/technical-documentation/islandora-middleware-services-api.md
This PR addresses documentation issue #211. See commit history for versioning of the document - 1) intial conversion 2) changing ports to reflect php microservices and added link to original document. 
Also, @8282, whomever you are, please ignore this and my commit message ;) :+1: .
=> Sprint 002 Issue 211, documentation of micro services.

docs/user-documentation/intro-to-claw.md
An intro page with "about the Project" stuff and very broad descriptions or how it works and why it's better. Goes with #261
=> New documentation - Answers #261

docs/user-documentation/intro-to-claw.md
Meat in the burger and one less subtitle. #261
=> Update intro-to-claw.md for #261

install/configs/claw.cnd
There are a few unnecessary namespaces defined in the CND file. This PR removes those.
=> Prune JCR/MODE/test namespaces

install/Vagrantfile, install/scripts/drupal-console.sh, install/scripts/lamp-server.sh, install/scripts/loris.sh
Resolves #386 
Installing using composer seems to make it work with Drupal8. Also needed to remove the settings check as it is not working properly with PHP 7.
@MarcusBarnes @Natkeeran If you two could test this out and see if it works for you, that would be awesome.
=> Install drupal-console using composer

install/Vagrantfile, install/configs/karaf/fcrepo_camel_toolbox.script, install/configs/karaf/islandora_indexing_triplestore.script, install/configs/repository.json, install/configs/variables, install/scripts/blazegraph.sh, install/scripts/drupal.sh, install/scripts/fcrepo.sh
=> Update CLAW-vagrant to fcrepo 4.7.0; Address #423.

install/scripts/bootstrap.sh, install/scripts/fcrepo.sh
Resolves #458 and #459 
After pulling in these changes and running `vagrant up`, the Fedora webapp should deploy and you should be able to access the admin UI.  Also, check catalina.out and you shouldn't see the errors we were previously getting.  See this gist: https://gist.github.com/dannylamb/cea486a82d1467baf70d67bf40e8f9b9
=> Restoring group write perms to fcrepo4 data dir

install/configs/karaf/alpaca.script, install/scripts/alpaca.sh, install/scripts/config.sh, install/scripts/islandora-karaf-components.sh
This PR updates the install to include the changes from #448.
This will require you to spin up a new box, but since https://github.com/Islandora-CLAW/Alpaca/pull/22 won't be merged until you can test this, there's some extra hoops to jump through.  Pull in the changes from this PR and then
- `cd /path/to/CLAW/install`
- `vagrant destroy`
- `sed -i 's|git clone https://github.com/Islandora-CLAW/Alpaca.git|git clone -b broadcaster-448 https://github.com/dannylamb/Alpaca.git|' scripts/alpaca.sh`
- `vagrant up`
Then once the VM is up and ready, you can test by verifying the feature has installed itself properly.
- `/opt/karaf/bin/client`
And from within the Karaf console
```
karaf@root()> feature:list | grep islandora-connector-broadcast
islandora-connector-broadcast           | …
```
=> Broadcaster 448

README.md
Update link for 2017 Meetings (was pointed at 2016).
=> Update Meeting Link in Readme.md

docs/contributing/committers.md
As discussed in the January 25th Committers Call, this adds the irc nicknames of the CLAW Committers so that they can be more easily identified by people looking for help on irc.
=> Update committers.md to include irc nicks

docs/technical-documentation/docs-build.md, docs/technical-documentation/drupal-project.md, mkdocs.yml
**GitHub issue**: 
Follow-on to: https://github.com/Islandora-CLAW/drupal-project/pull/11
Adds syncing technical documentation for Drupal Project
Documentation
[Build the docs locally](http://islandora-claw.github.io/CLAW/technical-documentation/docs-build/).
=> Add Drupal Project syncing documentation

.scripts/travis_setup_drupal.sh
**GitHub Issue**: Part of https://github.com/Islandora-CLAW/CLAW/issues/618
Should unblock
- https://github.com/Islandora-CLAW/islandora/pull/59
- Islandora-CLAW/islandora_collection#20
- Islandora-CLAW/islandora_image#13 
Pins phpcs to 2.9 to _hopefully_ get Travis passing again.  Or if he fails, at least it's not because of phpcs failing to execute.
Updated the `composer require` for phpcs to use ^2.9
Merge and re-start the affected Travis builds.
=> Pinning phpcs to 2.9 for Islandora-CLAW/CLAW#618

mkdocs.yml
Adds link to intro to LD doc.
Build docs locally, and make sure it is there.
I'll push up to gh-pages once merged.
Here is a super easy one @Islandora-CLAW/committers -- need to get this updated for the CLAW FAQ asap.
=> Add links LD docs missed in #616

.scripts/travis_setup_drupal.sh
**GitHub Issue**: #670
This is a short-term fix to deal with the fact that exporting blocks ties you to the theme.  Long-term we need to figure out a solution to decouple us from any particular theme.
Copy/paste from claw_vagrant to set up Carapace.
After this is merged we need to re-run the tests for islandora_collection and make sure they pass.
Any @Islandora-CLAW/committers feeling lucky?
=> Using carapace in Travis build

docs/contributing/committers.md
* Other Relevant Links : [Listserv announcement](https://groups.google.com/d/msg/islandora/hQTlxVZN3Mc/1pYR83l7AQAJ)
Updates Committers document to include our latest CLAW Committer.
Added Natkeeran Ledchumykanthan to the list and expanded the tables a bit to accommodate our longest name so far.
A visual test should do it. Just a documentation update.
@dannylamb I guess?
=> Update committers.md - Add new Committer Natkeeran Ledchumykanthan

docs/contributing/committers.md
* Other Relevant Links: [CLAW call agenda/minutes](https://github.com/Islandora-CLAW/CLAW/wiki/May-16,-2018#agenda)
Updates Committers document to include our latest CLAW Committer.
Added info on new committer Seth Shaw.
Build the docs using mkdocs following these instructions
http://islandora-claw.github.io/CLAW/technical-documentation/docs-build/
Then see the changes locally on 
http://localhost:8111/contributing/committers/
This is only the commit that changes the documentation content. At this time I need the help of a CLAW committer to first [install mkdocs and build the CLAW docs](http://islandora-claw.github.io/CLAW/technical-documentation/docs-build/) AND THEN run the following mkdocs command...
`mkdocs gh-deploy --clean`
This command will then deploy the documentation content to …
=> Add Seth Shaw to the CLAW Committers list

docs/technical-documentation/docs-build.md, docs/technical-documentation/drupal-project.md, docs/technical-documentation/versioning.md
This commit fixes a handful of small typos.
No new documentation content added, just fixes typos.
Review the diff to see if my spelling corrections are incorrect.
I found the typos using the [aspell](https://en.wikipedia.org/wiki/GNU_Aspell) CLI spell checker.
=> Fixed a few small typos in the CLAW docs using aspell CLI utility

docs/install/README.md, docs/technical-documentation/versioning.md, mkdocs.yml
A couple small fixes.
* Make the install link point to claw-playbook now that claw_vagrant is removed
* Fix a typo
* Remove reference to claw_vagant in versioning documents
=> Remove claw_vagrant, fix typo, link install to claw-playbook.

.scripts/travis_setup_drupal.sh
I was wrong, so the `-n` test meant to test if there **is** a value. So if `$COMPOSER_PATH` has a value then **don't** use it. 
So I was wrong, `-z` checks for an empty value.
Also, `composer drupal-scaffold` doesn't work until you run `composer update`.
This should get us past the original memory outage to a new one which is [this one](https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors)
Based on my test there is swap defined so I'm not sure what we can do.
@Islandora-CLAW/committers especially @dannylamb
=> Inverted test

README.md
**GitHub Issue**: Resolves https://github.com/Islandora-CLAW/CLAW/issues/883
Links to the docs in the readme
=> Linking to project documentation in README

.scripts/travis_setup_drupal.sh
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/931
Unblocks: https://github.com/Islandora-CLAW/islandora/pull/99
Removes code that was manually installing and old version (^2.9) of `coder_sniffer`, which is now in conflict with what is supported by `drupal/coder` (^3.0).
Getting rid of a call to composer to install `coder_sniffer`, so that `drupal/coder` can pull in the version it needs transitively.
Can't, but once merged, Travis should stop blowing up on `phpcs` calls.
@Islandora-CLAW/committers @MarcusBarnes
=> Letting drupal/coder dictate the version of coder_sniffer

.scripts/travis_setup_drupal.sh
**GitHub Issue**: Goes with https://github.com/Islandora-CLAW/islandora_demo/pull/16
Updates the travis script that provisions drupal to pull in the pdf.js library
Some shot in the dark bash changes.  Downloads and unzips the pdf.js javascript library and `composer require`s and `drush en`s the `pdf` contrib module.
Not entirely sure.  This has to get merged before we can restart the build on https://github.com/Islandora-CLAW/islandora_demo/pull/16
This will most likely require some iteration (unless I'm unwittingly a bash master)
@Islandora-CLAW/committers, specifically @Natkeeran
=> Updating travis provisioner for pdf.js

docs/technical-documentation/docs_style_guide.md
**GitHub Issue**: #1040
Creates docs/technical-documentation/docs_style_guide.md as a place to have a documentation style guide.
A draft version of a documentation style guide based on simple suggestions I once got from @whikloj  
Review to see what corrections or additions should be made to the content.
=> First attempt at a docs style guide

docs/user-documentation/content_types.md
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1098
Attempts to fix some formatting issues so that [this page](https://islandora-claw.github.io/CLAW/user-documentation/content_types/) looks better.
* Change tips to notes
* add titles to all notes
* `-` instead of `*` for bulleted lists.
Implement that changes, rebuild the docs, and see if they look better now. 
I still have no idea why the images are broken. I can't find anything in the formatting for this page that differs from other pages where images are showing up fine. The images are in the assets folder, they're the same filetype as images that do work. I am :confused:
@dannylamb @whikloj @seth-shaw-unlv
=> Update content_types.md to fix formatting issues for mkdocs

docs/user-documentation/usage-stats.md
Adding basic documentation about web analytics/usage stats.
**GitHub Issue**: (link)
* https://github.com/Islandora-CLAW/CLAW/issues/792
* Basic documentation about web analytics/usage stats integration in Islandora 8.
Consider adding this to user documentation.
@manez 
=> User Documentation >> Usage Stats

docs/technical-documentation/testing-notes.md
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/881
Documents the Gemini Pseudo-field that shows the Fedora URI on a Node, Media, or Taxonomy Term. 
Does this give enough info to make it work?
Discussed at CLAW call 2019-05-08
=> Document the Gemini Pseudo-field.

mkdocs.yml
**GitHub Issue**: n/a
If you have an older version of mkdocs, then the current configuration works great. If you have a newer one (> 1.0) then you get the default colours (blue), fonts, and logos.
This updates the configuration, you should pull it down and test build it locally (`mkdocs serve`) to see that it appears the same as the one online https://islandora-claw.github.io/CLAW/
Build locally and see that same as online (above)
@Islandora-CLAW/committers @rosiel
=> Update mkdocs configuration
